// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/views/dashboards/analytics/AnalyticsProjectStatistics.tsx
// ** MUI Imports
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import Avatar from '@mui/material/Avatar'
import Typography from '@mui/material/Typography'
import CardHeader from '@mui/material/CardHeader'
import CardContent from '@mui/material/CardContent'

// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import OptionsMenu from 'src/@core/components/option-menu'

interface DataType {
  src: string
  title: string
  imgAlt: string
  subtitle: string
  chipText: string
  imgWidth: number
  imgHeight: number
}

const data: DataType[] = [
  {
    imgWidth: 22,
    imgHeight: 22,
    chipText: '$6,500',
    title: '3D Illustration',
    imgAlt: '3d-illustration',
    subtitle: 'Blender Illustration',
    src: '/images/cards/3d-illustration.png'
  },
  {
    imgWidth: 33,
    imgHeight: 22,
    chipText: '$4,290',
    subtitle: 'Figma UI Kit',
    title: 'Finance App Design',
    imgAlt: 'finance-app-design',
    src: '/images/cards/finance-app-design.png'
  },
  {
    imgWidth: 20,
    imgHeight: 22,
    title: '4 Square',
    imgAlt: '4-square',
    chipText: '$44,500',
    subtitle: 'Android Application',
    src: '/images/cards/4-square.png'
  },
  {
    imgWidth: 19,
    imgHeight: 22,
    chipText: '$12,690',
    title: 'Delta Web App',
    imgAlt: 'delta-web-app',
    subtitle: 'React Dashboard',
    src: '/images/cards/delta-web-app.png'
  },
  {
    imgWidth: 23,
    imgHeight: 22,
    chipText: '$10,850',
    subtitle: 'Vue + Laravel',
    title: 'eCommerce Website',
    imgAlt: 'ecommerce-website',
    src: '/images/cards/ecommerce-website.png'
  }
]

const AnalyticsProjectStatistics = () => {
  return (
    <Card>
      <CardHeader
        title='Project Statistics'
        action={
          <OptionsMenu
            options={['Refresh', 'Edit', 'Share']}
            iconButtonProps={{ size: 'small', className: 'card-more-options' }}
          />
        }
      />
      <CardContent>
        <Box sx={{ mb: 4, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Typography
            sx={{
              lineHeight: 2,
              fontWeight: 500,
              fontSize: '0.75rem',
              letterSpacing: '0.17px',
              textTransform: 'uppercase'
            }}
          >
            Name
          </Typography>
          <Typography
            sx={{
              lineHeight: 2,
              fontWeight: 500,
              fontSize: '0.75rem',
              letterSpacing: '0.17px',
              textTransform: 'uppercase'
            }}
          >
            Budget
          </Typography>
        </Box>
        {data.map((item: DataType, index: number) => {
          return (
            <Box
              key={item.title}
              sx={{
                display: 'flex',
                alignItems: 'center',
                mb: index !== data.length - 1 ? [4, 4, 5] : undefined
              }}
            >
              <Avatar variant='rounded' sx={{ mr: 3, width: 50, height: 42, backgroundColor: 'background.default' }}>
                <img alt='avatar' src={item.src} width={item.imgWidth} height={item.imgHeight} />
              </Avatar>
              <Box
                sx={{
                  width: '100%',
                  display: 'flex',
                  flexWrap: 'wrap',
                  alignItems: 'center',
                  justifyContent: 'space-between'
                }}
              >
                <Box sx={{ mr: 2, display: 'flex', mb: 0.4, flexDirection: 'column' }}>
                  <Typography variant='body2' sx={{ mb: 0.5, fontWeight: 600, color: 'text.primary' }}>
                    {item.title}
                  </Typography>
                  <Typography variant='caption'>{item.subtitle}</Typography>
                </Box>
                <CustomChip
                  skin='light'
                  size='small'
                  color='primary'
                  label={item.chipText}
                  sx={{ height: 20, fontSize: '0.75rem', fontWeight: 500 }}
                />
              </Box>
            </Box>
          )
        })}
      </CardContent>
    </Card>
  )
}

export default AnalyticsProjectStatistics

// wp-content/plugins/materialize-admin-v12.1.0/vue-version/javascript-version/full-version/src/views/dashboard/analytics/AnalyticsProjectStatistics.vue
<script setup>
import illustration3d from '@images/cards/3d-illustration.png'
import square4 from '@images/cards/4-square.png'
import deltaWebApp from '@images/cards/delta-web-app.png'
import ecommerceWebsite from '@images/cards/ecommerce-website.png'
import financeAppDesign from '@images/cards/finance-app-design.png'

const projects = [
  {
    chipText: '$6,500',
    title: '3D Illustration',
    subtitle: 'Blender Illustration',
    src: illustration3d,
  },
  {
    chipText: '$4,290',
    subtitle: 'Figma UI Kit',
    title: 'Finance App Design',
    src: financeAppDesign,
  },
  {
    title: '4 Square',
    chipText: '$44,500',
    subtitle: 'Android Application',
    src: square4,
  },
  {
    chipText: '$12,690',
    title: 'Delta Web App',
    subtitle: 'React Dashboard',
    src: deltaWebApp,
  },
  {
    chipText: '$10,850',
    subtitle: 'Vue + Laravel',
    title: 'eCommerce Website',
    src: ecommerceWebsite,
  },
]

const moreList = [
  {
    title: 'Last 28 Days',
    value: 'Last 28 Days',
  },
  {
    title: 'Last Month',
    value: 'Last Month',
  },
  {
    title: 'Last Year',
    value: 'Last Year',
  },
]
</script>

<template>
  <VCard title="Project Statistics">
    <template #append>
      <div class="me-n3 mt-n2">
        <MoreBtn :menu-list="moreList" />
      </div>
    </template>

    <VCardText>
      <VList class="card-list">
        <VListItem class="pb-0">
          <VListItemTitle class="text-xs font-weight-medium d-flex justify-space-between align-center mb-1">
            <span class="text-sm font-weight-medium">
              NAME
            </span>
            <span class="text-xs font-weight-medium">BUDGET</span>
          </VListItemTitle>
          <VDivider />
        </VListItem>

        <VListItem
          v-for="project in projects"
          :key="project.title"
        >
          <template #prepend>
            <VAvatar
              rounded
              size="45"
              variant="tonal"
              class="me-3"
            >
              <VImg
                :src="project.src"
                height="22"
              />
            </VAvatar>
          </template>

          <VListItemTitle class="font-weight-medium text-sm mb-1">
            {{ project.title }}
          </VListItemTitle>

          <VListItemSubtitle class="text-xs">
            {{ project.subtitle }}
          </VListItemSubtitle>

          <template #append>
            <VListItemAction>
              <VChip
                :text="project.chipText"
                color="primary"
                size="x-small"
                class="font-weight-medium"
              />
            </VListItemAction>
          </template>
        </VListItem>
      </VList>
    </VCardText>
  </VCard>
</template>

<style lang="scss" scoped>
.card-list {
  --v-card-list-gap: 1.125rem;
}
</style>
