// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/views/dashboards/crm/CrmAward.tsx
// ** MUI Imports
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import Button from '@mui/material/Button'
import { styled } from '@mui/material/styles'
import Typography from '@mui/material/Typography'
import CardContent from '@mui/material/CardContent'

// Styled component for the trophy image
const TrophyImg = styled('img')(({ theme }) => ({
  right: 22,
  bottom: 0,
  width: 106,
  position: 'absolute',
  [theme.breakpoints.down('sm')]: {
    width: 95
  }
}))

const CrmAward = () => {
  return (
    <Card sx={{ position: 'relative' }}>
      <CardContent>
        <Typography variant='h6'>
          Congratulations{' '}
          <Box component='span' sx={{ fontWeight: 'bold' }}>
            Norris
          </Box>
          ! 🎉
        </Typography>
        <Typography variant='body2' sx={{ mb: 3.25 }}>
          Best seller of the month
        </Typography>
        <Typography variant='h5' sx={{ fontWeight: 600, color: 'primary.main' }}>
          $42.8k
        </Typography>
        <Typography variant='body2' sx={{ mb: 3.25 }}>
          78% of target 🤟🏻
        </Typography>
        <Button size='small' variant='contained'>
          View Sales
        </Button>
        <TrophyImg alt='trophy' src='/images/cards/trophy.png' />
      </CardContent>
    </Card>
  )
}

export default CrmAward

// wp-content/plugins/materialize-admin-v12.1.0/vue-laravel-version/javascript-version/full-version/resources/js/views/dashboard/crm/CrmAward.vue
<script setup>
import trophy from '@images/misc/trophy.png'
</script>

<template>
  <VCard>
    <VCardItem class="pb-2">
      <VCardTitle class="text-wrap">
        <span class="me-1">Congratulations </span><strong class="me-1">Norris!</strong><span>🎉</span>
      </VCardTitle>
      <span class="text-sm">Best seller of the month</span>
    </VCardItem>

    <VCardText>
      <h5 class="text-h5 text-primary">
        $42.8k
      </h5>
      <p class="mb-3">
        78% of target 🤟🏻
      </p>

      <VBtn size="small">
        View Sales
      </VBtn>
    </VCardText>

    <!-- Trophy -->
    <VImg
      :src="trophy"
      class="trophy flip-in-rtl"
    />
  </VCard>
</template>

<style lang="scss">
.trophy {
  position: absolute;
  inline-size: 6.625rem;
  inset-block-end: 0;
  inset-inline-end: 1rem;
}
</style>
