// wp-content/plugins/materialize-admin-v12.1.0/react-version/javascript-version/full-version/src/pages/dashboards/crm/index.js
// ** MUI Imports
import Grid from '@mui/material/Grid'

// ** Icon Imports
import Icon from 'src/@core/components/icon'

// ** Custom Component Import
import CardStatisticsVertical from 'src/@core/components/card-statistics/card-stats-vertical'

// ** Styled Component Import
import ApexChartWrapper from 'src/@core/styles/libs/react-apexcharts'

// ** Demo Components Imports
import CrmAward from 'src/views/dashboards/crm/CrmAward'
import CrmTable from 'src/views/dashboards/crm/CrmTable'
import CrmTotalGrowth from 'src/views/dashboards/crm/CrmTotalGrowth'
import CrmTotalProfit from 'src/views/dashboards/crm/CrmTotalProfit'
import CrmMonthlyBudget from 'src/views/dashboards/crm/CrmMonthlyBudget'
import CrmExternalLinks from 'src/views/dashboards/crm/CrmExternalLinks'
import CrmWeeklyOverview from 'src/views/dashboards/crm/CrmWeeklyOverview'
import CrmPaymentHistory from 'src/views/dashboards/crm/CrmPaymentHistory'
import CrmOrganicSessions from 'src/views/dashboards/crm/CrmOrganicSessions'
import CrmProjectTimeline from 'src/views/dashboards/crm/CrmProjectTimeline'
import CrmMeetingSchedule from 'src/views/dashboards/crm/CrmMeetingSchedule'
import CrmSocialNetworkVisits from 'src/views/dashboards/crm/CrmSocialNetworkVisits'
import CrmMostSalesInCountries from 'src/views/dashboards/crm/CrmMostSalesInCountries'

const CrmDashboard = () => {
  return (
    <ApexChartWrapper>
      <Grid container spacing={6} className='match-height'>
        <Grid item xs={12} md={4}>
          <CrmAward />
        </Grid>
        <Grid item xs={6} sm={3} md={2}>
          <CardStatisticsVertical
            stats='155k'
            color='primary'
            trendNumber='+22%'
            title='Total Orders'
            chipText='Last 4 Month'
            icon={<Icon icon='mdi:cart-plus' />}
          />
        </Grid>
        <Grid item xs={6} sm={3} md={2}>
          <CardStatisticsVertical
            stats='$13.4k'
            color='success'
            trendNumber='+38%'
            title='Total Sales'
            chipText='Last Six Month'
            icon={<Icon icon='mdi:currency-usd' />}
          />
        </Grid>
        <Grid item xs={6} sm={3} md={2}>
          <CrmTotalProfit />
        </Grid>
        <Grid item xs={6} sm={3} md={2}>
          <CrmTotalGrowth />
        </Grid>
        <Grid item xs={12} md={4}>
          <CrmOrganicSessions />
        </Grid>
        <Grid item xs={12} md={8}>
          <CrmProjectTimeline />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmWeeklyOverview />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmSocialNetworkVisits />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmMonthlyBudget />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmMeetingSchedule />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmExternalLinks />
        </Grid>
        <Grid item xs={12} sm={6} md={4}>
          <CrmPaymentHistory />
        </Grid>
        <Grid item xs={12} md={4}>
          <CrmMostSalesInCountries />
        </Grid>
        <Grid item xs={12} md={8}>
          <CrmTable />
        </Grid>
      </Grid>
    </ApexChartWrapper>
  )
}

export default CrmDashboard

// wp-content/plugins/materialize-admin-v12.1.0/vue-laravel-version/javascript-version/full-version/resources/js/pages/dashboards/crm.vue
<script setup>
import CrmAward from '@/views/dashboard/crm/CrmAward.vue'
import CrmExternalLinks from '@/views/dashboard/crm/CrmExternalLinks.vue'
import CrmGrowthDonutCharts from '@/views/dashboard/crm/CrmGrowthDonutCharts.vue'
import CrmMeetingSchedule from '@/views/dashboard/crm/CrmMeetingSchedule.vue'
import CrmMonthlyBudget from '@/views/dashboard/crm/CrmMonthlyBudget.vue'
import CrmMostSalesInCountries from '@/views/dashboard/crm/CrmMostSalesInCountries.vue'
import CrmOrganicSessions from '@/views/dashboard/crm/CrmOrganicSessions.vue'
import CrmPaymentHistory from '@/views/dashboard/crm/CrmPaymentHistory.vue'
import CrmProfitBarWithGapCharts from '@/views/dashboard/crm/CrmProfitBarWithGapCharts.vue'
import CrmProjectTimeline from '@/views/dashboard/crm/CrmProjectTimeline.vue'
import CrmSocialNetworkVisits from '@/views/dashboard/crm/CrmSocialNetworkVisits.vue'
import CrmUserList from '@/views/dashboard/crm/CrmUserList.vue'
import CrmWeeklyOverview from '@/views/dashboard/crm/CrmWeeklyOverview.vue'
</script>

<template>
  <VRow class="match-height">
    <!-- 👉 Award -->
    <VCol
      cols="12"
      md="4"
    >
      <CrmAward />
    </VCol>

    <!-- 👉 Total Orders -->
    <VCol
      cols="12"
      sm="3"
      md="2"
    >
      <CardStatisticsVertical
        v-bind="{
          title: 'Total Orders',
          color: 'primary',
          icon: 'mdi-cart-plus',
          stats: '155k',
          change: 22,
          subtitle: 'Last 4 Month',
        }"
      />
    </VCol>

    <!-- 👉 Total Sales -->
    <VCol
      cols="12"
      sm="3"
      md="2"
    >
      <CardStatisticsVertical
        v-bind="{
          title: 'Total Sales',
          color: 'success',
          icon: 'mdi-currency-usd',
          stats: '$13.4k',
          change: 38,
          subtitle: 'Last Six Months',
        }"
      />
    </VCol>

    <!-- 👉 Profile Line Charts -->
    <VCol
      cols="12"
      sm="3"
      md="2"
    >
      <CrmProfitBarWithGapCharts />
    </VCol>

    <!-- 👉 Total Growth -->
    <VCol
      cols="12"
      md="2"
      sm="3"
    >
      <CrmGrowthDonutCharts />
    </VCol>

    <!-- 👉 Organic Sessions -->
    <VCol
      cols="12"
      md="4"
    >
      <CrmOrganicSessions />
    </VCol>

    <!-- 👉 Project Timeline -->
    <VCol
      cols="12"
      md="8"
    >
      <CrmProjectTimeline />
    </VCol>

    <!-- 👉 Weekly Overview -->
    <VCol
      cols="12"
      sm="6"
      md="4"
    >
      <CrmWeeklyOverview />
    </VCol>

    <!-- 👉 Social Network Visits -->
    <VCol
      cols="12"
      sm="6"
      md="4"
    >
      <CrmSocialNetworkVisits />
    </VCol>

    <!-- 👉 Monthly Budget -->
    <VCol
      cols="12"
      md="4"
      sm="6"
    >
      <CrmMonthlyBudget />
    </VCol>

    <!-- 👉 Meeting Schedule -->
    <VCol
      cols="12"
      md="4"
      sm="6"
    >
      <CrmMeetingSchedule />
    </VCol>

    <!-- 👉 External Links -->
    <VCol
      cols="12"
      sm="6"
      md="4"
    >
      <CrmExternalLinks />
    </VCol>

    <!-- 👉 Payment History -->
    <VCol
      cols="12"
      sm="6"
      md="4"
    >
      <CrmPaymentHistory />
    </VCol>

    <!-- 👉 Most Sales in Countries -->
    <VCol
      cols="12"
      md="4"
    >
      <CrmMostSalesInCountries />
    </VCol>

    <!-- 👉 User List -->
    <VCol
      cols="12"
      md="8"
    >
      <CrmUserList />
    </VCol>
  </VRow>
</template>

<style lang="scss">
@use "@core-scss/template/libs/apex-chart.scss";
</style>
