// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/views/ui/cards/widgets/CardWidgetsPerformanceOverview.tsx
// ** MUI Imports
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import { useTheme } from '@mui/material/styles'
import CardHeader from '@mui/material/CardHeader'
import Typography from '@mui/material/Typography'
import CardContent from '@mui/material/CardContent'

// ** Icon Imports
import Icon from 'src/@core/components/icon'

// ** Third Party Imports
import { ApexOptions } from 'apexcharts'

// ** Custom Components Imports
import OptionsMenu from 'src/@core/components/option-menu'
import ReactApexcharts from 'src/@core/components/react-apexcharts'

// ** Util Import
import { hexToRGBA } from 'src/@core/utils/hex-to-rgba'

const CardWidgetsPerformanceOverview = () => {
  // ** Hook
  const theme = useTheme()

  const options: ApexOptions = {
    chart: {
      parentHeightOffset: 0,
      toolbar: { show: false }
    },
    stroke: {
      curve: 'stepline'
    },
    colors: [hexToRGBA(theme.palette.warning.main, 1)],
    grid: {
      yaxis: {
        lines: { show: false }
      }
    },
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false }
    },
    yaxis: {
      labels: { show: false }
    }
  }

  return (
    <Card>
      <CardHeader
        title='Performance Overview'
        action={
          <OptionsMenu
            options={['Last 28 Days', 'Last Month', 'Last Year']}
            iconButtonProps={{ size: 'small', className: 'card-more-options' }}
          />
        }
      />
      <CardContent>
        <ReactApexcharts
          type='line'
          height={202}
          options={options}
          series={[{ data: [7, 65, 40, 7, 40, 80, 45, 65, 65] }]}
        />
        <Box
          sx={{
            mt: 4,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            '& svg': { mr: 1.5, color: 'warning.main' }
          }}
        >
          <Icon icon='mdi:circle' fontSize='0.75rem' />
          <Typography variant='body2' sx={{ color: 'text.disabled' }}>
            Avarage cost per interaction is $5.65
          </Typography>
        </Box>
      </CardContent>
    </Card>
  )
}

export default CardWidgetsPerformanceOverview

// wp-content/plugins/materialize-admin-v12.1.0/vue-version/typescript-version/full-version/src/views/pages/cards/card-widgets/CardWidgetsPerformanceOverview.vue
<script setup lang="ts">
import VueApexCharts from 'vue3-apexcharts'
import { useTheme } from 'vuetify'
import { hexToRgb } from '@layouts/utils'

const moreList = [
  { title: 'Last 28 Days', value: 'Last 28 Days' },
  { title: 'Last Month', value: 'Last Month' },
  { title: 'Last Year', value: 'Last Year' },
]

const vuetifyTheme = useTheme()

const chartConfig = computed(() => {
  const themeColors = vuetifyTheme.current.value.colors

  return {
    chart: {
      parentHeightOffset: 0,
      toolbar: { show: false },
    },
    stroke: {
      curve: 'stepline',
    },
    tooltip: { enabled: false },
    colors: [`rgba(${hexToRgb(String(themeColors.warning))}, 1)`],
    grid: {
      yaxis: {
        lines: { show: false },
      },
    },
    xaxis: {
      labels: { show: false },
      axisTicks: { show: false },
      axisBorder: { show: false },
    },
    yaxis: {
      labels: { show: false },
    },
  }
})

const series = [{ data: [7, 65, 40, 7, 40, 80, 45, 65, 65] }]
</script>

<template>
  <VCard title="Performance Overview">
    <template #append>
      <div class="me-n3 mt-n2">
        <MoreBtn :menu-list="moreList" />
      </div>
    </template>

    <VCardText>
      <VueApexCharts
        type="line"
        height="202"
        :options="chartConfig"
        :series="series"
      />
      <div class="d-flex align-center justify-center gap-2">
        <VBadge
          dot
          color="warning"
        />
        <span class="text-disabled mt-2">Average cost per interaction is $5.65</span>
      </div>
    </VCardText>
  </VCard>
</template>
