// wp-content/plugins/materialize-admin-v12.1.0/vue-laravel-version/javascript-version/full-version/resources/js/views/dashboard/crm/CrmMeetingSchedule.vue
<script setup>
import avatar4 from '@images/avatars/avatar-2.png'
import avatar3 from '@images/avatars/avatar-3.png'
import avatar1 from '@images/avatars/avatar-4.png'
import avatar2 from '@images/avatars/avatar-5.png'
import avatar6 from '@images/avatars/avatar-7.png'
import avatar5 from '@images/avatars/avatar-8.png'

const meetingSchedules = [
  {
    type: 'Business',
    title: 'Call with Woods',
    avatar: avatar1,
    dateTime: '21 Jul | 08:20-10:30',
  },
  {
    type: 'Dinner',
    title: 'Conference call',
    avatar: avatar2,
    dateTime: '28 Jul | 05:00-6:45',
  },
  {
    type: 'Meetup',
    title: 'Meeting with Mark',
    avatar: avatar3,
    dateTime: '03 Aug | 07:00-8:30',
  },
  {
    type: 'Dinner',
    title: 'Meeting in Oakland',
    avatar: avatar4,
    dateTime: '14 Feb | 04:15-05:30',
  },
  {
    type: 'Meditation',
    title: 'Call with Hilda',
    avatar: avatar5,
    dateTime: '24 Jul | 11:30-12:00',
  },
  {
    type: 'Business',
    title: 'Meeting with Carl',
    avatar: avatar6,
    dateTime: '05 Oct | 10:00-12:45',
  },
]

const moreList = [
  {
    title: 'Last 28 Days',
    value: 'Last 28 Days',
  },
  {
    title: 'Last Month',
    value: 'Last Month',
  },
  {
    title: 'Last Year',
    value: 'Last Year',
  },
]

const resolveChipColor = meetingType => {
  if (meetingType === 'Business')
    return 'primary'
  if (meetingType === 'Dinner')
    return 'warning'
  if (meetingType === 'Meetup')
    return 'secondary'
  if (meetingType === 'Dinner')
    return 'error'
  if (meetingType === 'Meditation')
    return 'success'
}
</script>

<template>
  <VCard title="Meeting Schedule">
    <template #append>
      <div class="me-n3 mt-n2">
        <MoreBtn :menu-list="moreList" />
      </div>
    </template>

    <VCardText>
      <VList
        lines="two"
        class="meeting-schedule-list card-list"
      >
        <VListItem
          v-for="meeting in meetingSchedules"
          :key="meeting.title"
        >
          <!-- 👉 Avatar  -->
          <template #prepend>
            <VAvatar
              rounded
              :size="38"
              :image="meeting.avatar"
              class="me-3"
            />
          </template>

          <!-- 👉 Title and Subtitle -->
          <VListItemTitle class="text-sm font-weight-medium mb-1">
            {{ meeting.title }}
          </VListItemTitle>

          <VListItemSubtitle class="text-xs text-no-wrap d-flex align-center">
            <VIcon
              start
              :size="16"
              icon="mdi-calendar-blank"
            />
            <span>{{ meeting.dateTime }}</span>
          </VListItemSubtitle>

          <!-- 👉 Business Types -->
          <template #append>
            <VChip
              size="x-small"
              :color="resolveChipColor(meeting.type)"
              :text="meeting.type"
            />
          </template>
        </VListItem>
      </VList>
    </VCardText>
  </VCard>
</template>

<style lang="scss" scoped>
.card-list {
  --v-card-list-gap: 1.5625rem;
}
</style>

<style lang="scss">
.meeting-schedule-list {
  .v-list-item__append {
    block-size: 100%;
  }
}
</style>

// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/views/dashboards/crm/CrmMeetingSchedule.tsx
// ** MUI Imports
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import Avatar from '@mui/material/Avatar'
import Typography from '@mui/material/Typography'
import CardHeader from '@mui/material/CardHeader'
import CardContent from '@mui/material/CardContent'

// ** Icon Imports
import Icon from 'src/@core/components/icon'

// ** Types
import { ThemeColor } from 'src/@core/layouts/types'

// ** Custom Components
import CustomChip from 'src/@core/components/mui/chip'
import OptionsMenu from 'src/@core/components/option-menu'

interface DataType {
  src: string
  title: string
  subtitle: string
  chipText: string
  chipColor: ThemeColor
}

const data: DataType[] = [
  {
    chipText: 'Business',
    chipColor: 'primary',
    title: 'Call with Woods',
    src: '/images/avatars/4.png',
    subtitle: '21 Jul | 08:20-10:30'
  },
  {
    chipText: 'Dinner',
    chipColor: 'warning',
    title: 'Conference call',
    src: '/images/avatars/5.png',
    subtitle: '28 Jul | 05:00-6:45'
  },
  {
    chipText: 'Meetup',
    chipColor: 'secondary',
    title: 'Meeting with Mark',
    src: '/images/avatars/3.png',
    subtitle: '03 Aug | 07:00-8:30'
  },
  {
    chipText: 'Dinner',
    chipColor: 'error',
    title: 'Meeting in Oakland',
    src: '/images/avatars/2.png',
    subtitle: '14 Feb | 04:15-05:30'
  },
  {
    chipColor: 'success',
    chipText: 'Meditation',
    title: 'Call with Hilda',
    src: '/images/avatars/8.png',
    subtitle: '24 Jul | 11:30-12:00'
  },
  {
    chipText: 'Business',
    chipColor: 'primary',
    title: 'Meeting with Carl',
    src: '/images/avatars/7.png',
    subtitle: '05 Oct | 10:00-12:45'
  }
]

const CrmMeetingSchedule = () => {
  return (
    <Card>
      <CardHeader
        title='Meeting Schedule'
        action={
          <OptionsMenu
            options={['Refresh', 'Edit', 'Share']}
            iconButtonProps={{ size: 'small', className: 'card-more-options' }}
          />
        }
      />
      <CardContent>
        {data.map((item: DataType, index: number) => {
          return (
            <Box
              key={item.title}
              sx={{
                display: 'flex',
                alignItems: 'center',
                mb: index !== data.length - 1 ? 6.5 : undefined
              }}
            >
              <Avatar src={item.src} variant='rounded' sx={{ mr: 3, width: 38, height: 38 }} />
              <Box
                sx={{
                  width: '100%',
                  display: 'flex',
                  flexWrap: 'wrap',
                  alignItems: 'center',
                  justifyContent: 'space-between'
                }}
              >
                <Box sx={{ mr: 2, display: 'flex', mb: 0.4, flexDirection: 'column' }}>
                  <Typography variant='body2' sx={{ mb: 0.5, fontWeight: 600, color: 'text.primary' }}>
                    {item.title}
                  </Typography>
                  <Box
                    sx={{
                      display: 'flex',
                      alignItems: 'center',
                      '& svg': {
                        mr: 1.5,
                        color: 'text.secondary',
                        verticalAlign: 'middle'
                      }
                    }}
                  >
                    <Icon icon='mdi:calendar-blank-outline' fontSize='1rem' />
                    <Typography variant='caption'>{item.subtitle}</Typography>
                  </Box>
                </Box>
                <CustomChip
                  skin='light'
                  size='small'
                  label={item.chipText}
                  color={item.chipColor}
                  sx={{ height: 20, fontSize: '0.75rem', fontWeight: 500 }}
                />
              </Box>
            </Box>
          )
        })}
      </CardContent>
    </Card>
  )
}

export default CrmMeetingSchedule
