// wp-content/plugins/materialize-admin-v12.1.0/vue-version/javascript-version/full-version/src/views/pages/typography/TypographyTexts.vue
<template>
  <VCard title="Texts">
    <VCardText>
      <VRow no-gutters>
        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0"
        >
          <span class="text-subtitle-1 text-no-wrap">text-subtitle-1</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-subtitle-1 text-truncate mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 1rem / line-height: 1.75rem / font-weight: 400</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0 mb-1"
        >
          <span class="text-subtitle-2 text-no-wrap">text-subtitle-2</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-subtitle-2 mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 0.875rem / line-height: 1.375rem / font-weight: 500</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0"
        >
          <span class="text-body-1 text-no-wrap">text-body-1</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-body-1 mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 1rem / line-height: 1.5rem / font-weight: 400</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0 mb-1"
        >
          <span class="text-body-2 text-no-wrap">text-body-2</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-body-2 mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 0.875rem / line-height: 1.25rem / font-weight: 400</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0 mb-1"
        >
          <span class="text-caption">text-caption</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-caption mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 0.75rem / line-height: 1.25rem / font-weight: 400</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0 mb-1"
        >
          <span class="text-overline text-no-wrap">text-overline</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
          class="mb-6"
        >
          <p class="text-overline mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 0.75rem / line-height: 2rem / font-weight: 500</span>
        </VCol>

        <VCol
          cols="12"
          md="2"
          sm="4"
          class="py-0"
        >
          <span class="text-button">text-button</span>
        </VCol>
        <VCol
          cols="12"
          md="10"
        >
          <p class="text-button mb-1">
            Cupcake ipsum dolor sit amet fruitcake donut chocolate.
          </p>
          <span>font-size: 0.875rem / line-height: 2.25rem / font-weight: 500</span>
        </VCol>
      </VRow>
    </VCardText>
  </VCard>
</template>

// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/views/ui/typography/TypographyTexts.tsx
// ** MUI Imports
import Card from '@mui/material/Card'
import { styled } from '@mui/material/styles'
import CardHeader from '@mui/material/CardHeader'
import Typography from '@mui/material/Typography'
import CardContent from '@mui/material/CardContent'
import Grid, { GridProps } from '@mui/material/Grid'

const DemoGrid = styled(Grid)<GridProps>(({ theme }) => ({
  [theme.breakpoints.down('sm')]: {
    paddingTop: `${theme.spacing(1)} !important`
  }
}))

const TypographyTexts = () => {
  return (
    <Card>
      <CardHeader title='Texts' />
      <CardContent>
        <Grid container spacing={6}>
          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>subtitle1</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='subtitle1' sx={{ mb: 2 }}>
              Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.
            </Typography>
            <Typography variant='body2'>font-size: 16px / line-height: 28px / font-weight: 400</Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>subtitle2</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='subtitle2' sx={{ mb: 2 }}>
              Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.
            </Typography>
            <Typography variant='body2'>font-size: 14px / line-height: 21px / font-weight: 500</Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>body1</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography sx={{ mb: 2 }}>Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.</Typography>
            <Typography variant='body2'>font-size: 16px / line-height: 24px / font-weight: 400</Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>body2</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='body2' sx={{ mb: 2 }}>
              Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.
            </Typography>
            <Typography variant='body2'>font-size: 14px / line-height: 20px / font-weight: 400</Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>button</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='button'>Button Text</Typography>
            <Typography variant='body2' sx={{ mt: 2 }}>
              font-size: 14px / line-height: 17px / font-weight: 500 / text-transform: uppercase
            </Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>caption</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='caption'>Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.</Typography>
            <Typography variant='body2' sx={{ mt: 2 }}>
              font-size: 12px / line-height: 15px / font-weight: 400
            </Typography>
          </DemoGrid>

          <Grid item xs={12} sm={2} sx={{ display: 'flex', alignItems: 'center' }}>
            <Typography>overline</Typography>
          </Grid>
          <DemoGrid item xs={12} sm={10}>
            <Typography variant='overline'>Cupcake ipsum dolor sit amet chocolate bar pastry sesame snaps.</Typography>
            <Typography variant='body2' sx={{ mt: 1 }}>
              font-size: 12px / line-height: 15px / font-weight: 400 / text-transform: uppercase
            </Typography>
          </DemoGrid>
        </Grid>
      </CardContent>
    </Card>
  )
}

export default TypographyTexts
