// wp-content/plugins/materialize-admin-v12.1.0/react-version/typescript-version/full-version/src/pages/dashboards/ecommerce/index.tsx
// ** MUI Imports
import Grid from '@mui/material/Grid'

// ** Custom Components Imports
import CardStatisticsCharacter from 'src/@core/components/card-statistics/card-stats-with-image'

// ** Styled Component Import
import KeenSliderWrapper from 'src/@core/styles/libs/keen-slider'
import ApexChartWrapper from 'src/@core/styles/libs/react-apexcharts'

// ** Demo Components Imports
import EcommerceTable from 'src/views/dashboards/ecommerce/EcommerceTable'
import EcommerceTotalVisits from 'src/views/dashboards/ecommerce/EcommerceTotalVisits'
import EcommerceVisitsByDay from 'src/views/dashboards/ecommerce/EcommerceVisitsByDay'
import EcommerceLiveVisitors from 'src/views/dashboards/ecommerce/EcommerceLiveVisitors'
import EcommerceSalesOverview from 'src/views/dashboards/ecommerce/EcommerceSalesOverview'
import EcommerceWeeklySalesBg from 'src/views/dashboards/ecommerce/EcommerceWeeklySalesBg'
import EcommerceSalesThisMonth from 'src/views/dashboards/ecommerce/EcommerceSalesThisMonth'
import EcommerceMarketingSales from 'src/views/dashboards/ecommerce/EcommerceMarketingSales'
import EcommerceActivityTimeline from 'src/views/dashboards/ecommerce/EcommerceActivityTimeline'
import EcommerceImpressionsOrders from 'src/views/dashboards/ecommerce/EcommerceImpressionsOrders'
import EcommerceSalesOverviewWithTabs from 'src/views/dashboards/ecommerce/EcommerceSalesOverviewWithTabs'

const EcommerceDashboard = () => {
  return (
    <ApexChartWrapper>
      <KeenSliderWrapper>
        <Grid container spacing={6} className='match-height'>
          <Grid item xs={12} md={6}>
            <EcommerceSalesOverview />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <CardStatisticsCharacter
              data={{
                stats: '8.14k',
                title: 'Ratings',
                chipColor: 'primary',
                trendNumber: '+15.6%',
                chipText: 'Year of 2022',
                src: '/images/cards/card-stats-img-1.png'
              }}
            />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <CardStatisticsCharacter
              data={{
                stats: '12.2k',
                trend: 'negative',
                title: 'Sessions',
                chipColor: 'success',
                trendNumber: '-25.5%',
                chipText: 'Last Month',
                src: '/images/cards/card-stats-img-2.png'
              }}
            />
          </Grid>
          <Grid item xs={12} md={6}>
            <EcommerceWeeklySalesBg />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <EcommerceTotalVisits />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <EcommerceSalesThisMonth />
          </Grid>
          <Grid item xs={12} md={6}>
            <EcommerceActivityTimeline />
          </Grid>
          <Grid item xs={12} md={6}>
            <EcommerceSalesOverviewWithTabs />
          </Grid>
          <Grid item xs={12} sm={6} md={3}>
            <EcommerceImpressionsOrders />
          </Grid>
          <Grid item xs={12} md={5} sx={{ order: [2, 2, 1] }}>
            <EcommerceMarketingSales />
          </Grid>
          <Grid item xs={12} sm={6} md={4} sx={{ order: [1, 1, 2] }}>
            <EcommerceLiveVisitors />
          </Grid>
          <Grid item xs={12} md={8} sx={{ order: 3 }}>
            <EcommerceTable />
          </Grid>
          <Grid item xs={12} md={4} sx={{ order: 3 }}>
            <EcommerceVisitsByDay />
          </Grid>
        </Grid>
      </KeenSliderWrapper>
    </ApexChartWrapper>
  )
}

export default EcommerceDashboard

// wp-content/plugins/materialize-admin-v12.1.0/vue-laravel-version/typescript-version/full-version/resources/ts/pages/dashboards/ecommerce.vue
<script setup lang="ts">
import EcommerceActivityTimeline from '@/views/dashboard/ecommerce/EcommerceActivityTimeline.vue'
import EcommerceLiveVisitors from '@/views/dashboard/ecommerce/EcommerceLiveVisitors.vue'
import EcommerceMarketingSales from '@/views/dashboard/ecommerce/EcommerceMarketingSales.vue'
import EcommerceOrdersImpressions from '@/views/dashboard/ecommerce/EcommerceOrdersImpressions.vue'
import EcommerceSalesMonthCharts from '@/views/dashboard/ecommerce/EcommerceSalesMonthCharts.vue'
import EcommerceSalesOverview from '@/views/dashboard/ecommerce/EcommerceSalesOverview.vue'
import EcommerceTopReferralSources from '@/views/dashboard/ecommerce/EcommerceTopReferralSources.vue'
import EcommerceTotalVisits from '@/views/dashboard/ecommerce/EcommerceTotalVisits.vue'
import EcommerceUserList from '@/views/dashboard/ecommerce/EcommerceUserList.vue'
import EcommerceVisitsByDay from '@/views/dashboard/ecommerce/EcommerceVisitsByDay.vue'
import EcommerceWeeklySalesBg from '@/views/dashboard/ecommerce/EcommerceWeeklySalesBg.vue'
import illustration1 from '@images/cards/illustration-1.png'
import illustration2 from '@images/cards/illustration-2.png'

const statisticsWithImages = [
  {
    title: 'Ratings',
    subtitle: 'Year of 2021',
    stats: '8.14k',
    change: 15.6,
    image: illustration1,
    imgWidth: 99,
    color: 'primary',
  },
  {
    title: 'Sessions',
    subtitle: 'Last Month',
    stats: '12.2k',
    change: -25.5,
    image: illustration2,
    imgWidth: 85,
    color: 'success',
  },
]
</script>

<template>
  <VRow class="match-height">
    <!-- 👉 Sales Overview -->
    <VCol
      cols="12"
      md="6"
    >
      <EcommerceSalesOverview />
    </VCol>

    <!-- 👉 Images Cards -->
    <VCol
      v-for="statistics in statisticsWithImages"
      :key="statistics.title"
      cols="12"
      sm="6"
      md="3"
    >
      <CardStatisticsWithImages v-bind="statistics" />
    </VCol>

    <!-- 👉 Weekly Sales -->
    <VCol
      cols="12"
      md="6"
    >
      <EcommerceWeeklySalesBg />
    </VCol>

    <!-- 👉 Total Visits -->
    <VCol
      cols="12"
      md="3"
      sm="6"
    >
      <EcommerceTotalVisits />
    </VCol>

    <!-- 👉 Sales this months -->
    <VCol
      cols="12"
      md="3"
      sm="6"
    >
      <EcommerceSalesMonthCharts />
    </VCol>

    <!-- 👉 Activity Timeline -->
    <VCol
      cols="12"
      md="6"
    >
      <EcommerceActivityTimeline />
    </VCol>

    <!-- 👉 Top Referral Sources -->
    <VCol
      cols="12"
      md="6"
    >
      <EcommerceTopReferralSources />
    </VCol>

    <!-- 👉 Total Impressions -->
    <VCol
      cols="12"
      md="3"
    >
      <EcommerceOrdersImpressions />
    </VCol>

    <!-- 👉 Marketing and Sales -->
    <VCol
      cols="12"
      md="5"
    >
      <EcommerceMarketingSales />
    </VCol>

    <!-- 👉 Live Visitors -->
    <VCol
      cols="12"
      md="4"
    >
      <EcommerceLiveVisitors />
    </VCol>

    <!-- 👉 User list -->
    <VCol
      cols="12"
      md="8"
    >
      <EcommerceUserList />
    </VCol>

    <!-- 👉 Visits by day -->
    <VCol
      cols="12"
      md="4"
    >
      <EcommerceVisitsByDay />
    </VCol>
  </VRow>
</template>

<style lang="scss">
@use "@core-scss/template/libs/apex-chart.scss";
</style>
